package com.strategicgains.saga.event;

public enum SagaEventType
{
	SAGA_STARTED,
	SAGA_FAILED,
	SAGA_COMPENSATION_STARTED,
	SAGA_COMPENSATION_FAILED,
	SAGA_COMPENSATED,
	SAGA_COMPLETED,

	STEP_STARTED,
	STEP_COMPLETED,
	STEP_FAILED,
	STEP_COMPENSATION_STARTED,
	STEP_COMPENSATED,
	STEP_COMPENSATION_FAILED
}
